### ISSUE TITLE
Battle Brothers - Master Brother combat bike upgrade can be loaded multiple times

### ISSUE THREAD

**Issue by ScornMandark** [AdamLay/opr-army-forge#165]
Every time I load the list with a Master Brother with a Combat Bike, the option tree is reset to none even while the option is still kept on the brother.  I can then select the bike again, back out, reload the list, and keep doing it.  The bikes' guns keep getting added and the toughness is additive.  If I select jetpack or destroyer armor, it maintains thst option on reload, but it keeps all the bikes.  Selecting bikes again continues the process.

![Screenshot_20211102-132509_Chrome.jpg](https://user-images.githubusercontent.com/7913700/139919388-e3e04c2c-52ea-4d4a-b67f-da68995e8967.jpg)

**Comment by ScornMandark** [comment]
Reproduced with custodian brothers as well.

![Screenshot_20211108-210524_Chrome.jpg](https://user-images.githubusercontent.com/7913700/140924821-75310602-8a2d-481c-bf8d-0b8f0b1150da.jpg)

**Comment by arcanelviejo** [comment]
Reproduced it, and looked in the file battle-brothers.json locally
I saw two strange things
there are 2 instances of "type", at the start of the upgrade definition, with ArmyBookUpgradeOption and ArmyBookItem values.
But, there is also the label "Combat Bike (Fast, Impact(1), Twin Assault Rifle (24”,A2))", that doesn't match the rule in the interface. Is the local file used? Changing it have no effect.

**Comment by arcanelviejo** [comment]
Update: debugging in browser, saw error on JS console: _Warning: Each child in a list should have a unique "key" prop._
Checked in local storage value that the  "Twin Heavy Rifle" didn't have "key" entry.
Confirmed with Battle Brothers unit with rules to "Replace one Heavy Rifle" with an weapon without key entry ("Plasma Rifle") that the bug is more general: saving and reloading maintained the upgrade in the unit but reset the "Replace one Heavy Rifle" option to none, so it could be selected again, accumulating any option with a weapon.
