### ISSUE TITLE
Data Tool needs to be able to parse bulleted lists for Special Rules.

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#21]
Ex. GDF Human Defense Force v2.13's "Commander" special rule or AOF Duchies of Vinci v2.3's "Captain" and "Trickster" rules.

**Comment by AdamLay** [comment]
Done and have added unit tests for the 3 examples given above. One issue to note is that the "auto format" button in the data tool won't be able to put a newline after the last bullet rule since they do not end with a full stop... For example:

"...Crank Up: AP(+1) when shooting
• Assault Stance: +1 to melee rolls Good Shot: This model shoots at Quality 4+."

This will need to be done manually for now I'm afraid - open to suggestions.
