### ISSUE TITLE
Add grouping based on unit's rules

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#29]
Idea/note for filtering units by category. As there are not really any. A combination of size quality and special rules might allow for some solid categorization.

Size 1, hero rules => hero
Size 1, tough, defense 2+, impact => vehicle
Size 2+ => unit (well everything not in a category is unit)

**Comment by AdamLay** [comment]
Current rule is...
`  const isHero = (u) => u.specialRules.indexOf("Hero") > -1;
  const isLarge = (u) => isTough(u, 6);
  const isElite = (u) => isTough(u, 3);

  const unitGroups = {
    "Heroes": army.units.filter(isHero),
    "Core": army.units.filter(u => !isElite(u) && !isHero(u)),
    "Elite": army.units.filter(u => !isLarge(u) && !isHero(u) && isElite(u)),
    "Large": army.units.filter(u => isLarge(u) && !isHero(u))
  };`

**Comment by Darguth** [comment]
I'd add two more categories:
1. Aircraft, if the unit has that rule.
2. Artillery, if the unit has that rule.

In almost all cases these are very different types of units from the Large and Elites category they'd typically fall into with the current logic. Makes sense to differentiate them I think. Also, since the rules are unique to game systems (Aircraft to GDF, Artillery to AOF) we're really only adding 1 category to lists at most.

**Comment by AdamLay** [comment]
Aircraft and Artillery added
