### ISSUE TITLE
List sharing

### ISSUE THREAD

**Issue by LikeANinja** [AdamLay/opr-army-forge#305]
Stroke of genius right here!

This will likely need some work on Snickerdoodles end, depending on your capabilities in Vercel.

While there is no user integrations or anything, how about a way to "publish" a list which can be accessed by anybody. Hit publish and the json data is stored with a 6 character pin (case sensitive alphanumeric), that will give you scope to store LOADS of lists.

These lists are read only, because there is no protection for them (unless you wanted to also password protect them?). When you load the list up, they are loaded as per normal, but in a non autosave state so that they can be loaded up by other users or between devices. 

Whether they are stored as files on the server, or a nosql database, I think this could be a quick and simple way of giving this much needed (imo) feature life

**Comment by AdamLay** [comment]
Yeah to be fair I hadn't thought about it like this! Not a bad idea at all - I might just DIY one with the free tier of Azure and Cosmos DB, then wangle a domain from OPA like army-forge-api.onepagerule.com or something!

**Comment by AdamLay** [comment]
might need to do some kind of "store for 30 days since last access" kinda thing

could put a minimum point count, say like 200 for skirmish games and 750 for full fat games, will stop people cluttering with 2 model lists

Depends how you want to, even if you do want to handle, editing between devices
Passwording a list would work, you just need to decide how to deal with it
store a BCrypt hash alongside the list 🤷‍♂️
then allow the save if the hash matches
