### ISSUE TITLE
Number of models in unit numbers are not updating when adding additional models

### ISSUE THREAD

**Issue by SweepsUpGames** [AdamLay/opr-army-forge#367]
![image](https://user-images.githubusercontent.com/857351/200188700-5918facf-a8de-418a-847b-8815fd150016.png)
Example list: https://army-forge.onepagerules.com/list?listId=1667711025576

Setup:
- Create Ratman Army for Age of Fantasy
- Add "Warriors" unit to army list
- Add "Heavy Weapons Team" upgrade to unit
  - The number of models in the unit correctly updates to 11
- Add "Battle Master" to army list
- Click "Join to Unit" drop down
  - Warriors unit added before will show as having "10" models instead of the correct 11
  - Also once the units are joined the joint model count reads as "11" instead of the correct 12

**Comment by AdamLay** [comment]
Thank you! So the join to unit dropdown is definitely a bug - I'm just looking at the joined unit header part though and that's not actually a bug, it was intentional. Although it having been seen as such begs the question of whether or not it's actually correct! It's meant to be read as `Battle Master` and `Warriors [11]` although it could be more useful to show the overall size, since the attached hero does technically increase that... I'll swap it over and see how it looks. Thanks!

**Comment by SweepsUpGames** [comment]
Thank you! That was super fast and it looks great!
